deletes junk files from given folders
ANIRUDH-GHUB/file-organiser pull request #8
Opened 2022-03-16 16:36 UTC by srihithamandalapu

2022-03-16 17:14 UTC, ANIRUDH-GHUB commented
fixes #9

2022-03-17 10:25 UTC, ANIRUDH-GHUB commented on deleteJunkFiles.py
> +junkFilePaths = ["C://Windows//Prefetch","C://Windows//Temp","C://Users//WELCOME//AppData//Local//Temp"]
Please add this list to constants

2022-03-17 10:28 UTC, srihithamandalapu commented on deleteJunkFiles.py
> +junkFilePaths = ["C://Windows//Prefetch","C://Windows//Temp","C://Users//WELCOME//AppData//Local//Temp"]
yeah sure

2022-03-17 10:33 UTC, ANIRUDH-GHUB requested changes

2022-03-17 10:33 UTC, ANIRUDH-GHUB commented on deleteJunkFiles.py
> +junkFilePaths = ["C://Windows//Prefetch","C://Windows//Temp","C://Users//WELCOME//AppData//Local//Temp"]
Pleae add this  list to constansta

2022-03-17 10:44 UTC, ANIRUDH-GHUB approved these changes

2022-03-17 10:44 UTC, merged